// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PimVIII.Data;

namespace PimVIII.Migrations
{
    [DbContext(typeof(PimVIIIContext))]
    partial class PimVIIIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PimVIII.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<int>("CEP");

                    b.Property<string>("Cidade");

                    b.Property<string>("Estado");

                    b.Property<string>("Logradouro");

                    b.Property<int>("Numero");

                    b.Property<int>("PessoaID");

                    b.HasKey("Id");

                    b.HasIndex("PessoaID")
                        .IsUnique();

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("PimVIII.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CPF");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("PimVIII.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DDD");

                    b.Property<int>("Numero");

                    b.Property<int>("PessoaID");

                    b.Property<int>("TipoTelefones");

                    b.HasKey("Id");

                    b.HasIndex("PessoaID");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("PimVIII.Models.Endereco", b =>
                {
                    b.HasOne("PimVIII.Models.Pessoa", "Pessoa")
                        .WithOne("Endereco")
                        .HasForeignKey("PimVIII.Models.Endereco", "PessoaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PimVIII.Models.Telefone", b =>
                {
                    b.HasOne("PimVIII.Models.Pessoa", "Pessoa")
                        .WithMany("Telefones")
                        .HasForeignKey("PessoaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
